garrethil/Project2

views/layouts/main.handlebars
=> Main.handlerbars feature

controllers/api/index.js, controllers/home-routes.js
added api files, updated home-routes controller
=> add api files

db/schema.sql
edit schema to match all models.
=> Final Schema

config/connection.js, controllers/index.js, server.js
Fixed some minor naming bugs as well as connection issues to sequelize
=> Feature fixed bugs

db/schema.sql
set deb name for realestate app.
=> set db name

controllers/home-routes.js, public/css/style.css, views/signup.handlebars
Just finished implementing the views handlebars for the signup route "/signup".
! NOTE ! : This essentially takes the same form styling as the login views so do not get tripped out!
=> Feature signup page

controllers/home-routes.js, db/schema.sql, public/css/style.css, views/layouts/main.handlebars, views/login.handlebars
Just finished implementing the views handlebars for the login route "/login"
=> Login feature

controllers/api/buildingTypeRoutes.js, controllers/api/cityRoutes.js, controllers/api/index.js, controllers/api/listingRoutes.js, controllers/api/listingTypeRoutes.js
Creating all get routes for api Routes and their path through index.js in the api folder of Controllers.
=> Api routes

utils/auth.js
added middleware to check if user is loggedin
=> withAuth middleware

controllers/api/userRoutes.js, public/js/login.js
implementing the logic to handle the form submission from login page front-end and send the data into controllers/api in order to log the user in appropriately...
=> Feature login functionality

utils/helpers.js
create function with date parameter
=> formatDate helper

public/js/signup.js
Implementing the logic to handle the form submission from sign-up page front-end, and send the data into controllers/api in order to create the new user into our database
=> Feature signup page func

.env.Example, server.js
=> Feature connecting session

controllers/api/index.js, controllers/api/userRoutes.js, controllers/home-routes.js, controllers/index.js, views/layouts/main.handlebars
Created the logout functionality for when user wants to logout!
NOTE: DO NOT MERGE YET PLEASE WAIT FOR SESSION SET UP
=> Feature logout functionality

controllers/api/listingRoutes.js, controllers/home-routes.js, models/BuildingType.js, models/City.js, models/Listing.js, models/User.js, models/index.js, package-lock.json, package.json, seeds/cityData.js, seeds/index.js, seeds/listingData.js, seeds/userData.js, server.js
server should now run and seed with no errors.
=> Sort out Seeding errors. 

controllers/api/listingRoutes.js, controllers/home-routes.js, models/ListingType.js, seeds/buildingTypeData.js, seeds/listingTypeData.js, server.js, views/addlisting.handlebars
creating pull request for review
=> Jpeg handler

controllers/home-routes.js, views/homepage.handlebars
Implementing the homepafe views from the passed data in controllers
=> Homepage feature

controllers/api/userRoutes.js, controllers/home-routes.js, public/js/logout.js, public/js/signup.js, utils/helpers.js
Fixed bugs lying within the sign up, logout and user login
=> Feature bug fixes

views/homepage.handlebars
=> Updated card section in homepage view

public/css/style.css, server.js, views/homepage.handlebars, views/layouts/main.handlebars
=> Adaptiveness
